# Get Golf Data from datagolf.com
This notebook is created to help make functions that end up in `get_golf_data.py`. The functions should be tested here and then added to the *.py* file for production.

Getting data from [datagolf.com](https://datagolf.com/) will likely be more effective and consistent than building scrapers and crawlers from [pgatour.com](https://www.pgatour.com/).

In [4]:
import pandas as pd
import numpy as np
import requests
import pygolf
from importlib import reload
import csv

_ = reload(pygolf)

pd.options.display.min_rows = 25
pd.options.display.max_colwidth = 200
pd.options.display.max_columns = 50

In [5]:
dg = pygolf.datagolf()

test = dg.get_dg_rankings()

In [6]:
test

,last_updated,am,country,datagolf_rank,dg_id,dg_skill_estimate,owgr_rank,primary_tour,last_name,suffix,first_name
0,2023-04-17 13:04:55 UTC,0,ESP,1,19195,2.603012,1,PGA,Rahm,,Jon
1,2023-04-17 13:04:55 UTC,0,USA,2,18417,2.529387,2,PGA,Scheffler,,Scottie
2,2023-04-17 13:04:55 UTC,0,USA,3,15466,2.291553,4,PGA,Cantlay,,Patrick
3,2023-04-17 13:04:55 UTC,0,NIR,4,10091,2.182844,3,PGA,McIlroy,,Rory
4,2023-04-17 13:04:55 UTC,0,USA,5,19895,2.131035,5,PGA,Schauffele,,Xander
5,2023-04-17 13:04:55 UTC,0,USA,6,11676,1.931837,16,PGA,Finau,,Tony
6,2023-04-17 13:04:55 UTC,0,KOR,7,17488,1.706381,17,PGA,Im,,Sungjae
7,2023-04-17 13:04:55 UTC,0,USA,8,14636,1.704234,9,PGA,Spieth,,Jordan
8,2023-04-17 13:04:55 UTC,0,USA,9,22085,1.640405,13,PGA,Morikawa,,Collin
9,2023-04-17 13:04:55 UTC,0,USA,10,26651,1.632792,15,PGA,Young,,Cameron
10,2023-04-17 13:04:55 UTC,0,ENG,11,17646,1.605908,8,PGA,Fitzpatrick,,Matthew
11,2023-04-17 13:04:55 UTC,0,NOR,12,18841,1.542761,11,PGA,Hovland,,Viktor
...,...,...,...,...,...,...,...,...,...,...,...
488,2023-04-17 13:04:55 UTC,0,USA,489,26657,-1.156798,501,KFT,Fisk,,Steven
489,2023-04-17 13:04:55 UTC,0,AUS,490,13342,-1.157190,408,KFT,Gibson,,Rhein
490,2023-04-17 13:04:55 UTC,0,THA,491,14128,-1.161136,419,ASA,Charoenkul,,Gunn
491,2023-04-17 13:04:55 UTC,0,USA,492,25027,-1.163144,501,KFT,Hirschman,,Grant
492,2023-04-17 13:04:55 UTC,0,CAN,493,13404,-1.163155,407,PGA,Gligic,,Michael
493,2023-04-17 13:04:55 UTC,0,NOR,494,15651,-1.163565,501,KFT,Ventura,,Kristoffer
494,2023-04-17 13:04:55 UTC,0,JPN,495,14209,-1.165369,249,JPN,Kozuma,,Jinichiro
495,2023-04-17 13:04:55 UTC,0,CHN,496,13026,-1.170454,501,KFT,Zhang,,Xinjun
496,2023-04-17 13:04:55 UTC,0,USA,497,11594,-1.173914,501,KFT,McCarthy,,Dan
497,2023-04-17 13:04:55 UTC,0,USA,498,24956,-1.176426,501,KFT,Blanchet,,Chandler
498,2023-04-17 13:04:55 UTC,0,ESP,499,22259,-1.180412,296,EURO,Rey,,Alejandro Del
499,2023-04-17 13:04:55 UTC,1,USA,500,25091,-1.180957,501,AM,Choi,,Sam